version: "3.9"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - rabbitmq-network
    deploy:
      placement:
        constraints:
          - node.role == manager

  consul-server:
    image: consul:1.15
    command: >
      agent
      -server
      -ui
      -bootstrap-expect=3
      -client=0.0.0.0
      -retry-join=tasks.consul-server
      -datacenter=dc1
      -data-dir=/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - rabbitmq-network
    # volumes:
    #   - consul_data:/consul/data
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1 
        constraints:
          - node.role == manager
    ports:
      - target: 8500
        published: 3001
        protocol: tcp
        mode: host  # 使用 host 模式避免網路問題
      - target: 8600
        published: 8600
        protocol: udp
        mode: host
      - target: 8301
        published: 8301
        protocol: udp
        mode: host  # Serf LAN 端口
      - target: 8302
        published: 8302
        protocol: udp
        mode: host  # Serf WAN 端口
      - target: 8300
        published: 8300
        protocol: tcp
        mode: host  # RPC 端口

  rabbitmq:
    image: rabbitmq:4-management-alpine
    hostname: "{{.Service.Name}}-{{.Task.Slot}}.{{.Task.ID}}"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: test1234
      RABBITMQ_USE_LONGNAME: "true"
      RABBITMQ_ERLANG_COOKIE: "SWARM-COOKIE-SECRET-KEY-HERE"
      RABBITMQ_NODENAME: "rabbit@{{.Service.Name}}-{{.Task.Slot}}.{{.Task.ID}}"
    configs:
      - source: rabbitmq_config
        target: /etc/rabbitmq/rabbitmq.conf
      - source: rabbitmq_enabled_plugins
        target: /etc/rabbitmq/enabled_plugins
    networks:
      - rabbitmq-network
    deploy:
      endpoint_mode: dnsrr
      replicas: 3
      placement:
        max_replicas_per_node: 1 
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.swarm-test`)"
        - "traefik.http.routers.rabbitmq.entrypoints=web"
        - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
        - "prometheus.metrics.port=15692"
      resources:
        limits:
          cpus: "1"
          memory: "1g"
        reservations:
          cpus: "0.5"
          memory: "512m"

  prometheus:
    image: prom/prometheus
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    ports:
      - "3002:9090"
    networks:
      - rabbitmq-network
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - rabbitmq-network
    deploy:
      placement:
        constraints:
          - node.role == manager

  rabbitmq-producer:
    image: kevinypfan/rabbitmq-tester:latest
    environment:
      - MODE=producer
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://admin:test1234@rabbitmq:5672
      - QUEUE_NAME=test-queue
      - EXCHANGE_NAME=test-exchange
      - ROUTING_KEY=test.message
      - PORT=3000
      - AUTO_SEND=true
      - AUTO_SEND_INTERVAL=2000
    networks:
      - rabbitmq-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  rabbitmq-consumer:
    image: kevinypfan/rabbitmq-tester:latest
    environment:
      - MODE=consumer
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://admin:test1234@rabbitmq:5672
      - QUEUE_NAME=test-queue
      - EXCHANGE_NAME=test-exchange
      - ROUTING_KEY=test.message
    networks:
      - rabbitmq-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  

networks:
  rabbitmq-network:
    driver: overlay

configs:
  rabbitmq_config:
    file: ./rabbitmq.conf
  rabbitmq_enabled_plugins:
    file: ./enabled_plugins
  prometheus_config:
    file: ./prometheus.yml


# volumes:
#   consul_data:
