version: '3.8'

services:
  # Producer 實例
  rabbitmq-producer:
    image: kevinypfan/rabbitmq-tester:latest
    environment:
      - MODE=producer
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://admin:test1234@rabbitmq:5672
      - QUEUE_NAME=test-queue
      - EXCHANGE_NAME=test-exchange
      - ROUTING_KEY=test.message
      - PORT=3000
      - AUTO_SEND=true
      - AUTO_SEND_INTERVAL=700
    networks:
      - rabbitmq-ha_rabbitmq-network
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  rabbitmq-consumer:
    image: kevinypfan/rabbitmq-tester:latest
    environment:
      - MODE=consumer
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://admin:test1234@rabbitmq:5672
      - QUEUE_NAME=test-queue
      - EXCHANGE_NAME=test-exchange
      - ROUTING_KEY=test.message
    networks:
      - rabbitmq-ha_rabbitmq-network
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  


networks:
  rabbitmq-ha_rabbitmq-network:
    external: true
