version: '3.8'

services:
  # Producer 實例
  rabbitmq-producer:
    image: kevinypfan/rabbitmq-tester:latest
    environment:
      - MODE=producer
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://admin:test1234@rabbitmq:5672
      - QUEUE_NAME=test-queue
      - EXCHANGE_NAME=test-exchange
      - ROUTING_KEY=test.message
      - PORT=3000
      - AUTO_SEND=true
      - AUTO_SEND_INTERVAL=700
      - HEARTBEAT_INTERVAL=5000
    networks:
      - rabbitmq-ha_rabbitmq-network
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.producer.rule=PathPrefix(`/producer`)"
        - "traefik.http.routers.producer.entrypoints=web"
        - "traefik.http.routers.producer.service=producer"
        - "traefik.http.services.producer.loadbalancer.server.port=3000"
        - "traefik.http.middlewares.producer-strip.stripprefix.prefixes=/producer"
        - "traefik.http.routers.producer.middlewares=producer-strip"
        - "traefik.docker.network=rabbitmq-ha_rabbitmq-network"

  rabbitmq-consumer:
    image: kevinypfan/rabbitmq-tester:latest
    environment:
      - MODE=consumer
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://admin:test1234@rabbitmq:5672
      - QUEUE_NAME=test-queue
      - EXCHANGE_NAME=test-exchange
      - ROUTING_KEY=test.message
      - STATS_QUEUE=reliability-stats
      - STATS_EXCHANGE=stats-exchange
    networks:
      - rabbitmq-ha_rabbitmq-network
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # 可靠性統計收集器
  rabbitmq-stats:
    image: kevinypfan/rabbitmq-tester:latest
    environment:
      - MODE=stats
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://admin:test1234@rabbitmq:5672
      - STATS_QUEUE=reliability-stats
      - STATS_EXCHANGE=stats-exchange
      - STATS_REPORT_INTERVAL=30000
      - PORT=3000
    networks:
      - rabbitmq-ha_rabbitmq-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.stats.rule=PathPrefix(`/stats`)"
        - "traefik.http.routers.stats.entrypoints=web"
        - "traefik.http.routers.stats.service=stats"
        - "traefik.http.services.stats.loadbalancer.server.port=3000"
        - "traefik.http.middlewares.stats-strip.stripprefix.prefixes=/stats"
        - "traefik.http.routers.stats.middlewares=stats-strip"
        - "traefik.docker.network=rabbitmq-ha_rabbitmq-network"

networks:
  rabbitmq-ha_rabbitmq-network:
    external: true
