version: '3.8'

services:
  # Producer 實例
  rabbitmq-producer:
    image: kevinypfan/rabbitmq-tester:latest
    environment:
      - MODE=producer
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://admin:test1234@rabbitmq-1:5672,amqp://admin:test1234@rabbitmq-2:5672,amqp://admin:test1234@rabbitmq-3:5672
      - QUEUE_NAME=test-queue
      - EXCHANGE_NAME=test-exchange
      - ROUTING_KEY=test.message
      - PORT=3000
      - AUTO_SEND=true
      - AUTO_SEND_INTERVAL=5000
    ports:
      - "3000:3000"
    networks:
      - rabbitmq-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Consumer 實例
  rabbitmq-consumer:
    image: kevinypfan/rabbitmq-tester:latest
    environment:
      - MODE=consumer
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://admin:test1234@rabbitmq-1:5672,amqp://admin:test1234@rabbitmq-2:5672,amqp://admin:test1234@rabbitmq-3:5672
      - QUEUE_NAME=test-queue
      - EXCHANGE_NAME=test-exchange
      - ROUTING_KEY=test.message
    networks:
      - rabbitmq-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # 混合模式實例（用於測試）
  rabbitmq-both:
    image: kevinypfan/rabbitmq-tester:latest
    environment:
      - MODE=both
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://admin:test1234@rabbitmq-1:5672,amqp://admin:test1234@rabbitmq-2:5672,amqp://admin:test1234@rabbitmq-3:5672
      - QUEUE_NAME=test-queue
      - EXCHANGE_NAME=test-exchange
      - ROUTING_KEY=test.message
      - PORT=3001
      - AUTO_SEND=false
    ports:
      - "3001:3001"
    networks:
      - rabbitmq-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  rabbitmq-network:
    external: true
